# Gahan AI Hackathon - Cutting Behavior Detection Config
# Optimized for GPU training with F1 > 0.85

model:
  name: "CuttingDetector"
  backbone: "google/vit-large-patch16-224"
  hidden_dim: 768
  num_classes: 4  # Background, Car, MotorBike, EgoVehicle
  sequence_length: 5
  num_queries: 100
  
  # Temporal Encoder
  temporal_encoder:
    type: "bidirectional_gru"
    hidden_size: 384
    num_layers: 2
    dropout: 0.1
    use_attention: true
    attention_heads: 8
  
  # DETR-style decoder
  decoder:
    num_queries: 100
    num_layers: 6
    dropout: 0.1

# Data configuration
data:
  data_dir: "/content/distribution"
  train_split: "Train"
  val_split_ratio: 0.2
  image_size: [224, 224]
  num_workers: 4  # Increased for GPU
  pin_memory: true
  prefetch_factor: 2
  oversample_positive: 3
  
  # ROI settings for lane-cutting focus
  roi_filter: true
  roi_bounds: [480, 540, 1440, 1080]
  
  # Data augmentation
  augmentation:
    color_jitter: 0.2
    blur_prob: 0.1
    horizontal_flip: 0.5
    normalize: true

# Training configuration optimized for GPU
training:
  batch_size: 16  # Increased for GPU efficiency
  num_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
  
  # GPU optimizations
  use_amp: true  # Mixed precision for GPU speedup
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  
  # Loss configuration
  loss_weights:
    classification: 1.0
    bbox_regression: 5.0
    giou: 2.0
    cutting: 3.0
    sequence: 2.0
  
  # Optimizer settings
  optimizer: "adamw"
  scheduler_step_size: 15
  scheduler_gamma: 0.1
  
  # Target metrics
  target_f1: 0.85
  save_dir: "checkpoints"

# Evaluation settings
evaluation:
  iou_threshold: 0.5
  confidence_threshold: 0.3
  target_f1: 0.85

# Device configuration
device:
  use_cuda: true
  num_workers: 4
  pin_memory: true
  non_blocking: true

# Paths (legacy - keeping for compatibility)
paths:
  dataset_root: "/content/distribution"
  train_split: "Train"
  test_split: "Test"
  val_split_ratio: 0.2
  checkpoints: "checkpoints"
  logs: "logs" 